<Project>
  <!-- Versione condivisa dei package pubblici correlati. -->
  <PropertyGroup>
    <Version>0.1.8</Version>
    <Authors>Seguso</Authors>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/seguso/Segusum</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>
</Project>
