using Microsoft.CodeAnalysis;
using System.IO;
using System.Linq;

namespace Segusum.Scripting.Semantics;

/// <summary>Identifies source emitted by the Segusum DSL generator.</summary>
public static class SegusumGeneratedSource
{
    public const string Marker = "// <auto-generated by Segusum.Scripting.Generator />";

    public static bool IsGenerated(SyntaxTree tree)
        => tree.GetText().ToString().StartsWith(Marker, System.StringComparison.Ordinal)
            || IsLegacyGeneratorHint(tree.FilePath);

    public static bool IsGenerated(ISymbol symbol)
        => symbol.Locations.Any(location => location.SourceTree != null && IsGenerated(location.SourceTree));

    // Packages produced before the explicit marker existed leave only the
    // generator's canonical hint name in the design-time generated path.
    // This narrow compatibility check does not hide arbitrary generated code.
    private static bool IsLegacyGeneratorHint(string? path)
    {
        if (string.IsNullOrEmpty(path)) return false;
        var stablePath = path!;
        var file = Path.GetFileName(stablePath) ?? "";
        return file.StartsWith("Segusum.Generated.", System.StringComparison.Ordinal)
            && file.EndsWith(".g.cs", System.StringComparison.Ordinal)
            && stablePath.IndexOf("Segusum.Scripting.Generator", System.StringComparison.OrdinalIgnoreCase) >= 0;
    }
}
