using System;
using System.Collections.Generic;
using System.Linq;
namespace Segusum.Scripting.Core;
public static class DslParser
{
 public static (DslDocument Document,IReadOnlyList<DslDiagnostic> Diagnostics) Parse(DslSource s){var d=new List<DslDiagnostic>();var p=new Parser(s,DslLexer.Lex(s,d),d);return(new DslDocument(p.ParseDocument()),d);}
 private sealed class Parser
 {
  readonly DslSource source;readonly IReadOnlyList<DslToken> tokens;readonly List<DslDiagnostic> diagnostics;int position;
  public Parser(DslSource s,IReadOnlyList<DslToken> t,List<DslDiagnostic>d){source=s;tokens=t;diagnostics=d;}
  DslToken Current=>tokens[position];bool Is(string s)=>Current.Text==s;DslToken Take()=>tokens[position++];void Skip(){while(Current.Kind==DslTokenKind.NewLine||Current.Kind==DslTokenKind.Semicolon)Take();}string Word(){if(Current.Kind!=DslTokenKind.Identifier){Error("Expected identifier.");return "_error";}return Take().Text;}void Need(string s){if(Is(s))Take();else Error("Expected '"+s+"'.");}void Error(string s){diagnostics.Add(new("SEGDSL101",s,Current.Span));while(Current.Kind!=DslTokenKind.NewLine&&Current.Kind!=DslTokenKind.Semicolon&&Current.Kind!=DslTokenKind.EndOfFile)Take();}
  public IReadOnlyList<DslDeclaration> ParseDocument(){var r=new List<DslDeclaration>();Skip();while(Current.Kind!=DslTokenKind.EndOfFile){var s=Current.Span;var w=Word();if(w=="state")r.Add(State(s));else if(w=="def")r.Add(Function(s));else if(w=="combine")r.Add(Handler("combine",s));else if(w=="use")r.Add(Handler("use",s));else if(w=="add")r.Add(Cycle(s));else if(w=="var"){var n=Word();Need("=");Need("new-cycle");r.Add(new CycleDeclaration(n,s));}else if(w=="next")Word();else Error("Unexpected declaration '"+w+"'.");Skip();}return r;}
  StateDeclaration State(SourceSpan s){var n=Word();Need(":");var ty=Word();Need("=");return new(n,ty,Expression(),s);}
  FunctionDeclaration Function(SourceSpan s){var n=Word();var p=new List<(string,string)>();while(!Is("ret")&&!Is(":")&&Current.Kind!=DslTokenKind.NewLine){var pn=Word();Need(":");p.Add((pn,Word()));if(Is(","))Take();}string? ret=null;if(Is("ret")){Take();ret=Word();}return new(n,p,ret,Block(),s);}
  HandlerDeclaration Handler(string kind,SourceSpan s){var first=Word();string? second=null;string? target=null;if(kind=="combine"){Need("with");second=Word();}else if(Is("for")){Take();kind="use-for";target=Word();}else kind="use-here";var b=Block();var phrase=b.OfType<DialogueStatement>().FirstOrDefault(x=>x.Character=="__phrase")?.Text is LiteralExpression l?l.Value:null;var exp=b.OfType<DialogueStatement>().FirstOrDefault(x=>x.Character=="__exp")?.Text is IdentifierExpression e?e.Name:null;var cond=b.OfType<DialogueStatement>().FirstOrDefault(x=>x.Character=="__possible")?.Text;var body=b.Where(x=>x is not DialogueStatement {Character:"__phrase" or "__exp" or "__possible"}).ToArray();return new(kind,first,second,target,phrase,exp,cond,body,s);}
  CycleElementDeclaration Cycle(SourceSpan s){var c=Word();var id=Word();var im=Is("important");if(im)Take();var b=Block(false);var when=b.OfType<DialogueStatement>().FirstOrDefault(x=>x.Character=="__when")?.Text;return new(c,id,im,when,b.Where(x=>x is not DialogueStatement {Character:"__when"}).ToArray(),s);}
  IReadOnlyList<DslStatement> Block(bool colon=true){if(colon)Need(":");Skip();var r=new List<DslStatement>();while(!Is("end")&&Current.Kind!=DslTokenKind.EndOfFile){var s=Current.Span;var w=Word();if(w=="if")r.Add(If(s));else if(w=="ret")r.Add(new ReturnStatement(Expression(),s));else if(w=="nar")r.Add(new NarStatement(Expression(),s));else if(w=="call"){position--;r.Add(new CallStatement(Expression(),s));}else if(w=="var"){var n=Word();Need("=");r.Add(new VariableDeclaration(n,Expression(),s));}else if(w=="next")r.Add(new NextCycleStatement(Expression(),s));else if(w=="add")r.Add(Add(s));else if(w=="phrase")r.Add(new DialogueStatement("__phrase",Expression(),s));else if(w=="exp")r.Add(new DialogueStatement("__exp",Expression(),s));else if(w=="possible-when")r.Add(new DialogueStatement("__possible",Expression(),s));else if(w=="when")r.Add(new DialogueStatement("__when",Expression(),s));else if(w=="makes-no-sense")r.Add(new MakesNoSenseStatement(s));else if(w=="finish-game")r.Add(new FinishGameStatement(s));else if(w=="do-not-advance-time")r.Add(new DoNotAdvanceTimeStatement(s));else if(Is(":")){Take();r.Add(new DialogueStatement(w,Expression(),s));}else if(Is("++")){Take();r.Add(new IncrementStatement(w,s));}else if(Is("=")||Is("+=")||Is("-=")){var op=Take().Text;r.Add(new AssignmentStatement(w,op,Expression(),s));}else Error("Unknown statement.");Skip();}Need("end");return r;}
  AddCycleElementStatement Add(SourceSpan s){var c=Word();var id=Word();var im=Is("important");if(im)Take();return new(c,id,im,null,Block(false),s);}
  IfStatement If(SourceSpan s){var c=Expression();var b=Block();return new(new[]{(c,b)},null,s);}
  DslExpression Expression(int min=0){var left=Prefix();while(true){var op=Current.Text;var p=op=="or"?1:op=="and"?2:op is "==" or "!=" or ">" or ">=" or "<" or "<="?3:0;if(p<=min)break;Take();left=new BinaryExpression(op,left,Expression(p),left.Span);}return left;}
  DslExpression Prefix(){var s=Current.Span;if(Is("not")){Take();return new UnaryExpression("not",Prefix(),s);}if(Is("call")){Take();var n=Word();var a=new List<DslArgument>();while(Current.Kind==DslTokenKind.Identifier||Current.Kind==DslTokenKind.Number||Current.Kind==DslTokenKind.String||Current.Kind==DslTokenKind.LParen){var q=Current.Span;a.Add(new(null,Prefix(),q));}return new CallExpression(n,a,s);}if(Current.Kind==DslTokenKind.LParen){Take();var e=Expression();Need(")");return new ParenthesizedExpression(e,s);}if(Current.Kind==DslTokenKind.String)return new LiteralExpression(Take().Text,"string",s);if(Current.Kind==DslTokenKind.Number)return new LiteralExpression(Take().Text,"number",s);var id=new IdentifierExpression(Word(),s);if(Is("not-seen-recently")){Take();return new CallExpression("not-seen-recently",new[]{new DslArgument(null,id,s),new DslArgument(null,Prefix(),Current.Span)},s);}return id;}
 }
}
