using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Segusum.Scripting.Core;

namespace Segusum.Scripting.Generator;

[Generator]
public sealed class SegusumGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor Error = new("SEGDSL200", "Segusum DSL error", "{0}", "Segusum DSL", DiagnosticSeverity.Error, true);
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var files = context.AdditionalTextsProvider.Where(x => x.Path.EndsWith(".seg", StringComparison.OrdinalIgnoreCase))
            .Select((x, ct) => new DslSource(x.Path, x.GetText(ct)?.ToString() ?? ""));
        context.RegisterSourceOutput(files.Collect().Combine(context.CompilationProvider), (sp, pair) => Generate(sp, pair.Left, pair.Right));
    }
    private static void Generate(SourceProductionContext sp, ImmutableArray<DslSource> sources, Compilation compilation)
    {
        var parsed = sources.Select(x => (Source: x, Result: DslParser.Parse(x))).ToArray();
        foreach (var item in parsed) foreach (var diagnostic in item.Result.Diagnostics) sp.ReportDiagnostic(Diagnostic.Create(Error, ToLocation(diagnostic.Span), diagnostic.Message));
        var worlds = compilation.Assembly.GlobalNamespace.GetNamespaceMembers().SelectMany(NamespaceTypes).Where(x => DerivesWorldBase(x)).ToArray();
        if (worlds.Length != 1) { sp.ReportDiagnostic(Diagnostic.Create(Error, Location.None, worlds.Length == 0 ? "No concrete World deriving from Seg.WorldBase was found." : "More than one concrete World deriving from Seg.WorldBase was found.")); return; }
        var declarations = parsed.SelectMany(x => x.Result.Document.Declarations).ToArray();
        var sb = new StringBuilder("// <auto-generated />\n#nullable enable\nusing Seg;\n");
        sb.Append("namespace ").Append(worlds[0].ContainingNamespace.ToDisplayString()).Append(";\n\n");
        sb.Append("partial class ").Append(worlds[0].Name).AppendLine("\n{");
        foreach (var state in declarations.OfType<StateDeclaration>()) sb.Append(" private ").Append(Type(state.Type)).Append(' ').Append(Name(state.Name)).Append(" = ").Append(Emit(state.Initializer)).AppendLine(";");
        foreach (var cycle in declarations.OfType<CycleDeclaration>()) sb.Append(" private readonly Cycle ").Append(Name(cycle.Variable)).AppendLine(" = new Cycle();");
        foreach (var function in declarations.OfType<FunctionDeclaration>()) EmitFunction(sb, function);
        sb.AppendLine(" protected override void configureGeneratedActionHandlers()\n {");
        foreach (var handler in declarations.OfType<HandlerDeclaration>()) EmitHandler(sb, handler, sp);
        foreach (var element in declarations.OfType<CycleElementDeclaration>()) EmitCycleElement(sb, element, sp, "  ");
        foreach (var next in declarations.OfType<NextCycleDeclaration>()) sb.Append("  execNextInCycle(").Append(Emit(next.Cycle)).AppendLine(");");
        sb.AppendLine(" }\n}");
        sp.AddSource("Segusum.Generated.g.cs", sb.ToString());
    }
    private static Location ToLocation(SourceSpan span) => Location.Create(span.Path, new Microsoft.CodeAnalysis.Text.TextSpan(span.Start, span.Length), new Microsoft.CodeAnalysis.Text.LinePositionSpan(new(span.Line - 1, span.Column - 1), new(span.Line - 1, span.Column - 1 + Math.Max(1, span.Length))));
    private static IEnumerable<INamedTypeSymbol> NamespaceTypes(INamespaceSymbol ns) { foreach (var t in ns.GetTypeMembers()) yield return t; foreach (var n in ns.GetNamespaceMembers()) foreach (var t in NamespaceTypes(n)) yield return t; }
    private static bool DerivesWorldBase(INamedTypeSymbol type) { for (var b = type.BaseType; b != null; b = b.BaseType) if (b.ToDisplayString() == "Seg.WorldBase") return true; return false; }
    private static void EmitFunction(StringBuilder sb, FunctionDeclaration function)
    { sb.Append(" private ").Append(Type(function.ReturnType ?? "void")).Append(' ').Append(Name(function.Name)).Append('(').Append(string.Join(",", function.Parameters.Select(x => Type(x.Type) + " " + Name(x.Name)))).AppendLine(")\n {"); foreach (var statement in function.Body) EmitStatement(sb, statement, "  ", null); sb.AppendLine(" }"); }
    private static void EmitHandler(StringBuilder sb, HandlerDeclaration handler, SourceProductionContext sp)
    {
        if (handler.Kind == "combine") sb.Append("  addHandlerCombine(").Append(Name(handler.First)).Append(',').Append(Name(handler.Second!)).Append(',').Append(Emit(handler.Phrase ?? new LiteralExpression("\"\"", "string", handler.Span)));
        else if (handler.Kind == "use-for") sb.Append("  addHandlerUseFor(").Append(Name(handler.First)).Append(',').Append(Name(handler.Target!));
        else sb.Append("  addHandlerUseHere(").Append(Name(handler.First));
        if (handler.Explanation != null && handler.Kind == "use-for") sb.Append(", ").Append(Emit(handler.Explanation));
        else if (handler.Explanation != null && handler.Kind == "combine") sb.Append(", explanation: ").Append(Emit(handler.Explanation));
        else if (handler.Explanation != null) sp.ReportDiagnostic(Diagnostic.Create(Error, ToLocation(handler.Explanation.Span), "Explanation is not supported by the use-here runtime API."));
        if (handler.Kind == "use-here" && handler.Phrase != null) sb.Append(", ").Append(Emit(handler.Phrase));
        sb.Append(", handler: e => {\n"); foreach (var statement in handler.Body) EmitStatement(sb, statement, "   ", "e"); sb.Append("  }");
        if (handler.Condition != null) sb.Append(", isPossibleNow: () => ").Append(Emit(handler.Condition)); sb.AppendLine(");");
    }
    private static void EmitCycleElement(StringBuilder sb, CycleElementDeclaration element, SourceProductionContext sp, string indent)
    { EmitAdd(sb, element.Cycle, element.Id, element.Important, element.Condition, element.Body, sp, indent); }
    private static void EmitAdd(StringBuilder sb, string cycle, string id, bool important, DslExpression? condition, IReadOnlyList<DslStatement> body, SourceProductionContext sp, string indent)
    {
        sb.Append(indent).Append(Name(cycle)).Append(".addToCycle(\"").Append(id.Replace("\"", "\\\"")).Append('"');
        if (important) sb.Append(", Importance.Important");
        if (condition != null) sb.Append(", x => ").Append(Emit(condition));
        sb.Append(", x => {\n"); foreach (var statement in body) EmitStatement(sb, statement, indent + "  ", null); sb.Append(indent).AppendLine("});");
    }
    private static void EmitStatement(StringBuilder sb, DslStatement statement, string indent, string? input)
    {
        switch (statement)
        {
            case VariableDeclaration v: sb.Append(indent).Append("var ").Append(Name(v.Name)).Append(" = ").Append(Emit(v.Initializer)).AppendLine(";"); break;
            case AssignmentStatement a: sb.Append(indent).Append(Name(a.Name)).Append(a.Operator).Append(Emit(a.Value)).AppendLine(";"); break;
            case IncrementStatement i: sb.Append(indent).Append(Name(i.Name)).AppendLine("++;"); break;
            case ReturnStatement r: sb.Append(indent).Append("return ").Append(Emit(r.Expression)).AppendLine(";"); break;
            case CallStatement c: sb.Append(indent).Append(Emit(c.Expression)).AppendLine(";"); break;
            case NarStatement n: sb.Append(indent).Append("narText(").Append(Emit(n.Text)).AppendLine(");"); break;
            case NarRoomStatement n: sb.Append(indent).Append("narRoom(").Append(Emit(n.Text)).Append(", curRoom, false, false);").AppendLine(); break;
            case DialogueStatement d: sb.Append(indent).Append("dial(").Append(Name(d.Character)).Append(',').Append(Emit(d.Text)).AppendLine(");"); break;
            case NextCycleStatement n: sb.Append(indent).Append("execNextInCycle(").Append(Emit(n.Cycle)).AppendLine(");"); break;
            case AddCycleElementStatement a: EmitAdd(sb, a.Cycle, a.Id, a.Important, a.Condition, a.Body, default, indent); break;
            case IfStatement i:
                for (var index = 0; index < i.Branches.Count; index++) { sb.Append(indent).Append(index == 0 ? "if (" : "else if (").Append(Emit(i.Branches[index].Condition)).AppendLine(")\n" + indent + "{"); foreach (var child in i.Branches[index].Body) EmitStatement(sb, child, indent + "  ", input); sb.Append(indent).AppendLine("}"); }
                if (i.ElseBody != null) { sb.Append(indent).AppendLine("else\n" + indent + "{"); foreach (var child in i.ElseBody) EmitStatement(sb, child, indent + "  ", input); sb.Append(indent).AppendLine("}"); } break;
            case MakesNoSenseStatement when input != null: sb.Append(indent).Append(input).AppendLine(".makesNoSenseAtThisTime = true;"); break;
            case FinishGameStatement when input != null: sb.Append(indent).Append(input).AppendLine(".gameFinished = true;"); break;
            case DoNotAdvanceTimeStatement when input != null: sb.Append(indent).Append(input).AppendLine(".timeMustAdvance = false;"); break;
            default: sb.Append(indent).AppendLine("/* SEGDSL: unsupported statement */"); break;
        }
    }
    private static string Emit(DslExpression expression) => expression switch
    {
        IdentifierExpression i => i.Name == "it" ? "x" : Name(i.Name), LiteralExpression l => l.Value,
        ParenthesizedExpression p => "(" + Emit(p.Expression) + ")", UnaryExpression u => (u.Operator == "not" ? "!" : u.Operator) + Emit(u.Operand),
        BinaryExpression b => Emit(b.Left) + " " + (b.Operator == "and" ? "&&" : b.Operator == "or" ? "||" : b.Operator) + " " + Emit(b.Right),
        CallExpression c when c.Name == "not-seen-recently" => Emit(c.Arguments[0].Expression) + ".notSeenRecently(" + Emit(c.Arguments[1].Expression) + ")",
        CallExpression c when c.Name == "was-seen-at-least-once" => "wasSeenAtLeastOnce(new CycleElemId(\"" + (c.Arguments[0].Expression is IdentifierExpression i ? i.Name : Emit(c.Arguments[0].Expression)) + "\"))",
        CallExpression c => Name(c.Name) + "(" + string.Join(",", c.Arguments.Select(a => Emit(a.Expression))) + ")", _ => "default"
    };
    private static string Name(string name) { var x = name.Contains('-') ? DslNames.Camel(name) : name; return x is "object" or "string" or "int" or "bool" ? "@" + x : x; }
    private static string Type(string type) => type == "int" ? "int" : type == "bool" ? "bool" : type == "string" ? "string" : type == "DateTime" ? "System.DateTime" : type;
}
