using System.Collections.Immutable;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Segusum.Scripting.Core;

namespace Segusum.Scripting.Generator;

[Generator]
public sealed class SegusumGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor ParseError = new("SEGDSL001", "Segusum DSL error", "{0}", "Segusum DSL", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor DuplicateId = new("SEGDSL005", "Duplicate CycleElementId", "CycleElementId '{0}' is declared more than once", "Segusum DSL", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor DuplicateCombine = new("SEGDSL006", "Duplicate combine handler", "A combine handler for '{0}' -> '{1}' is already declared", "Segusum DSL", DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor MissingMember = new("SEGDSL007", "Unknown World member", "World member '{0}' was not found", "Segusum DSL", DiagnosticSeverity.Error, true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var files = context.AdditionalTextsProvider
            .Where(x => x.Path.EndsWith(".seg", StringComparison.OrdinalIgnoreCase))
            .Select((x, ct) => new DslSource(x.Path, x.GetText(ct)?.ToString() ?? ""));
        var input = files.Collect().Combine(context.CompilationProvider);
        context.RegisterSourceOutput(input, static (spc, pair) => Generate(spc, pair.Left, pair.Right));
    }

    private static void Generate(SourceProductionContext context, ImmutableArray<DslSource> sources, Compilation compilation)
    {
        var docs = new List<(DslSource Source, DslDocument Document)>();
        foreach (var source in sources)
        {
            var parsed = DslParser.Parse(source);
            foreach (var diagnostic in parsed.Diagnostics)
                context.ReportDiagnostic(Diagnostic.Create(ParseError, Location.None, diagnostic.Message));
            docs.Add((source, parsed.Document));
        }
        var declarations = docs.SelectMany(x => x.Document.Declarations).ToArray();
        var ids = new HashSet<string>(StringComparer.Ordinal);
        foreach (var element in declarations.OfType<CycleElementDeclaration>())
            if (!ids.Add(element.Id)) context.ReportDiagnostic(Diagnostic.Create(DuplicateId, Location.None, element.Id));
        var combines = new HashSet<string>(StringComparer.Ordinal);
        foreach (var handler in declarations.OfType<HandlerDeclaration>().Where(x => x.Kind == "combine"))
            if (!combines.Add(handler.First + "\0" + handler.Second)) context.ReportDiagnostic(Diagnostic.Create(DuplicateCombine, Location.None, handler.First, handler.Second));

        var world = compilation.GetTypeByMetadataName("MinimalGame.World") ?? compilation.GetSymbolsWithName("World", SymbolFilter.Type).OfType<INamedTypeSymbol>().FirstOrDefault();
        var sb = new StringBuilder("// <auto-generated />\n#nullable enable\nusing Seg;\n");
        var ns = world?.ContainingNamespace?.IsGlobalNamespace == false ? world.ContainingNamespace.ToDisplayString() : "MinimalGame";
        sb.Append("namespace ").Append(ns).Append(";\n\npublic sealed partial class World\n{\n");
        foreach (var state in declarations.OfType<StateDeclaration>())
            sb.Append("    private ").Append(CSharpType(state.Type)).Append(' ').Append(SafeName(state.Name)).Append(" = ").Append(state.Initializer).AppendLine(";");
        foreach (var function in declarations.OfType<FunctionDeclaration>()) EmitFunction(sb, function);
        sb.AppendLine("    protected override void configureGeneratedActionHandlers()\n    {\n");
        sb.AppendLine("        var __seg_cyc = new Seg.Cycle();");
        foreach (var handler in declarations.OfType<HandlerDeclaration>()) EmitHandler(sb, handler, world, context);
        foreach (var element in declarations.OfType<CycleElementDeclaration>()) EmitCycleElement(sb, element);
        sb.AppendLine("    }\n}");
        context.AddSource("Segusum.Generated.g.cs", sb.ToString());
    }

    private static void EmitFunction(StringBuilder sb, FunctionDeclaration f)
    {
        var ret = CSharpType(f.ReturnType ?? "void");
        sb.Append("    private ").Append(ret).Append(' ').Append(SafeName(f.Name)).Append('(');
        sb.Append(string.Join(", ", f.Parameters.Select(p => CSharpType(p.Type) + " " + SafeName(p.Name)))); sb.AppendLine(")"); sb.AppendLine("    {");
        foreach (var line in f.Body) EmitStatement(sb, line, "        ");
        sb.AppendLine("    }");
    }

    private static void EmitHandler(StringBuilder sb, HandlerDeclaration h, INamedTypeSymbol? world, SourceProductionContext context)
    {
        var first = Resolve(h.First, world); var second = Resolve(h.Second, world); var target = Resolve(h.Target, world);
        if (first is null) context.ReportDiagnostic(Diagnostic.Create(MissingMember, Location.None, h.First));
        if (second is null && h.Kind == "combine") context.ReportDiagnostic(Diagnostic.Create(MissingMember, Location.None, h.Second));
        if (target is null && h.Kind == "use-for") context.ReportDiagnostic(Diagnostic.Create(MissingMember, Location.None, h.Target));
        var sentence = h.Phrase is null ? "\"\"" : h.Phrase;
        if (h.Kind == "combine") sb.Append("        addHandlerCombine(").Append(SafeName(h.First)).Append(", ").Append(SafeName(h.Second!)).Append(", ").Append(sentence).Append(", handler: e => {\n");
        else if (h.Kind == "use-for") sb.Append("        addHandlerUseFor(").Append(SafeName(h.First)).Append(", ").Append(SafeName(h.Target!)).Append(", handler: e => {\n");
        else sb.Append("        addHandlerUseHere(").Append(SafeName(h.First)).Append(", handler: e => {\n");
        foreach (var line in h.Body.Where(x => !x.StartsWith("phrase ") && !x.StartsWith("exp ") && !x.StartsWith("possible-when "))) EmitStatement(sb, line, "            ");
        sb.Append("        }");
        if (h.Condition is not null) sb.Append(", isPossibleNow: () => ").Append(Expr(h.Condition));
        sb.AppendLine(");");
    }

    private static void EmitCycleElement(StringBuilder sb, CycleElementDeclaration e)
    {
        sb.Append("        __seg_cyc.addToCycle(\"").Append(e.Id).Append("\"");
        if (e.Important) sb.Append(", Seg.Importance.Important");
        if (e.Condition is not null) sb.Append(", x => ").Append(Expr(e.Condition.Replace("it", "x")));
        sb.AppendLine(", x => { });");
    }

    private static void EmitStatement(StringBuilder sb, string line, string indent)
    {
        if (line.StartsWith("ret ")) { sb.Append(indent).Append("return ").Append(Expr(line.Substring(4))).AppendLine(";"); return; }
        if (line.StartsWith("nar ")) { sb.Append(indent).Append("narText(").Append(line.Substring(4)).AppendLine(");"); return; }
        var dialog = Regex.Match(line, "^(\\S+):\\s*(.+)$");
        if (dialog.Success) { sb.Append(indent).Append("dial(").Append(SafeName(dialog.Groups[1].Value)).Append(", ").Append(dialog.Groups[2].Value).AppendLine(");"); return; }
        if (line.StartsWith("call ")) { sb.Append(indent).Append(Call(line.Substring(5))).AppendLine(";"); return; }
        if (line.EndsWith("++")) { sb.Append(indent).Append(SafeName(line.Substring(0, line.Length - 2).Trim())).AppendLine("++;"); return; }
        if (line.StartsWith("if ")) { sb.Append(indent).Append("if (").Append(Expr(line.Substring(3).Trim('(', ')'))).AppendLine(") { }"); return; }
    }
    private static string Call(string value)
    {
        var p = value.Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries); var name = SafeName(p[0]);
        return name + "(" + string.Join(", ", p.Skip(1).Select(x => x.Contains(':') ? Expr(x.Substring(x.IndexOf(':') + 1)) : Expr(x))) + ")";
    }
    private static string Expr(string value)
    {
        value = value.Trim();
        if (value.Length >= 2 && value[0] == '(' && value[value.Length - 1] == ')') value = value.Substring(1, value.Length - 2).Trim();
        if (value.StartsWith("call ")) return Call(value.Substring(5));
        value = value.Replace(" is-in-world", ".is_in_world()").Replace(" not-seen-recently ", ".notSeenRecently(").Replace(" was-seen-at-least-once", ".wasSeenAtLeastOnce");
        if (value.Contains(".notSeenRecently(") && !value.EndsWith(")")) value += ")";
        value = Regex.Replace(value, @"[A-Za-z][A-Za-z0-9]*(?:-[A-Za-z][A-Za-z0-9]*)+", m => DslNames.Camel(m.Value));
        value = Regex.Replace(value, @"\bnot\s+", "!");
        return value.Replace(" and ", " && ").Replace(" or ", " || ");
    }
    private static string SafeName(string name)
    {
        var value = name.Contains('-') ? DslNames.Camel(name) : name;
        return value is "object" or "string" or "int" or "bool" ? "@" + value : value;
    }
    private static string CSharpType(string type) => type == "int" ? "int" : type == "bool" ? "bool" : type == "string" ? "string" : type == "DateTime" ? "System.DateTime" : type;
    private static ISymbol? Resolve(string? name, INamedTypeSymbol? world) => name is null || world is null ? null : DslNames.Candidates(name).SelectMany(n => world.GetMembers(n)).FirstOrDefault();
}
