using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Segusum.Scripting.Core;
namespace Segusum.Scripting.Generator;

[Generator]
public sealed class SegusumGenerator : IIncrementalGenerator
{
 static readonly DiagnosticDescriptor Error=new("SEGDSL200","Segusum DSL error","{0}","Segusum DSL",DiagnosticSeverity.Error,true);
 public void Initialize(IncrementalGeneratorInitializationContext c){var f=c.AdditionalTextsProvider.Where(x=>x.Path.EndsWith(".seg",StringComparison.OrdinalIgnoreCase)).Select((x,ct)=>new DslSource(x.Path,x.GetText(ct)?.ToString()??""));c.RegisterSourceOutput(f.Collect().Combine(c.CompilationProvider),(sp,p)=>Generate(sp,p.Left,p.Right));}
 static void Generate(SourceProductionContext sp,ImmutableArray<DslSource> sources,Compilation compilation)
 {
  var docs=sources.Select(x=>(x,DslParser.Parse(x))).ToArray();foreach(var x in docs)foreach(var d in x.Item2.Diagnostics)sp.ReportDiagnostic(Diagnostic.Create(Error,Location.Create(d.Span.Path,new Microsoft.CodeAnalysis.Text.TextSpan(d.Span.Start,d.Span.Length),new Microsoft.CodeAnalysis.Text.LinePositionSpan(new(d.Span.Line-1,d.Span.Column-1),new(d.Span.Line-1,d.Span.Column-1+d.Span.Length))),d.Message));
  var world=compilation.Assembly.GlobalNamespace.GetNamespaceMembers().SelectMany(NamespaceTypes).Where(x=>x.Name=="World"&&Derives(x,"Seg.WorldBase")).ToArray();if(world.Length!=1){sp.ReportDiagnostic(Diagnostic.Create(Error,Location.None,world.Length==0?"No concrete World deriving from Seg.WorldBase was found.":"More than one concrete World deriving from Seg.WorldBase was found."));return;}
  var all=docs.SelectMany(x=>x.Item2.Document.Declarations).ToArray();var sb=new StringBuilder("// <auto-generated />\n#nullable enable\nusing Seg;\n");sb.Append("namespace ").Append(world[0].ContainingNamespace.ToDisplayString()).Append(";\n\n");sb.Append("public sealed partial class ").Append(world[0].Name).AppendLine("\n{");
  foreach(var x in all.OfType<StateDeclaration>())sb.Append(" private ").Append(Type(x.Type)).Append(' ').Append(Name(x.Name)).Append(" = ").Append(Emit(x.Initializer)).AppendLine(";");
  foreach(var f in all.OfType<FunctionDeclaration>())EmitFunction(sb,f);
  sb.AppendLine(" protected override void configureGeneratedActionHandlers()\n {");foreach(var x in all.OfType<CycleDeclaration>())sb.Append("  var ").Append(Name(x.Variable)).AppendLine(" = new Cycle();");foreach(var x in all.OfType<HandlerDeclaration>())EmitHandler(sb,x);foreach(var x in all.OfType<CycleElementDeclaration>())EmitCycle(sb,x);sb.AppendLine(" }\n}");sp.AddSource("Segusum.Generated.g.cs",sb.ToString());
 }
 static IEnumerable<INamedTypeSymbol> NamespaceTypes(INamespaceSymbol n){foreach(var t in n.GetTypeMembers())yield return t;foreach(var x in n.GetNamespaceMembers())foreach(var t in NamespaceTypes(x))yield return t;}
 static bool Derives(INamedTypeSymbol t,string name){for(var b=t.BaseType;b!=null;b=b.BaseType)if(b.ToDisplayString()==name)return true;return false;}
 static void EmitFunction(StringBuilder s,FunctionDeclaration f){s.Append(" private ").Append(Type(f.ReturnType??"void")).Append(' ').Append(Name(f.Name)).Append('(').Append(string.Join(",",f.Parameters.Select(x=>Type(x.Type)+" "+Name(x.Name)))).AppendLine(")\n {");foreach(var x in f.Body)EmitStatement(s,x,"  ");s.AppendLine(" }");}
 static void EmitHandler(StringBuilder s,HandlerDeclaration h){if(h.Kind=="combine")s.Append("  addHandlerCombine(").Append(Name(h.First)).Append(',').Append(Name(h.Second!)).Append(',').Append(h.Phrase??"\"\"");else if(h.Kind=="use-for")s.Append("  addHandlerUseFor(").Append(Name(h.First)).Append(',').Append(Name(h.Target!));else s.Append("  addHandlerUseHere(").Append(Name(h.First));if(h.Explanation!=null)s.Append(h.Kind=="use-for"?", ex: ":", explanation: ").Append(Name(h.Explanation));s.Append(", handler: e => {\n");foreach(var x in h.Body)EmitStatement(s,x,"   ");s.Append("  }");if(h.Condition!=null)s.Append(", isPossibleNow: () => ").Append(Emit(h.Condition));s.AppendLine(");");}
 static void EmitCycle(StringBuilder s,CycleElementDeclaration x){s.Append("  ").Append(Name(x.Cycle)).Append(".addToCycle(\"").Append(x.Id).Append("\"");if(x.Important)s.Append(", Importance.Important");s.Append(", x => { ");foreach(var b in x.Body)EmitStatement(s,b,"");s.AppendLine(" });");}
 static void EmitStatement(StringBuilder s,DslStatement x,string i){switch(x){case ReturnStatement r:s.Append(i).Append("return ").Append(Emit(r.Expression)).AppendLine(";");break;case NarStatement n:s.Append(i).Append("narText(").Append(Emit(n.Text)).AppendLine(");");break;case DialogueStatement d:s.Append(i).Append("dial(").Append(Name(d.Character)).Append(',').Append(Emit(d.Text)).AppendLine(");");break;case CallStatement c:s.Append(i).Append(Emit(c.Expression)).AppendLine(";");break;case IncrementStatement z:s.Append(i).Append(Name(z.Name)).AppendLine("++;");break;case AssignmentStatement a:s.Append(i).Append(Name(a.Name)).Append(a.Operator).Append(Emit(a.Value)).AppendLine(";");break;case NextCycleStatement n:s.Append(i).Append("return ").Append(Emit(n.Cycle)).AppendLine(";");break;}}
 static string Emit(DslExpression x){switch(x){case IdentifierExpression i:return i.Name=="it"?"x":Name(i.Name);case LiteralExpression l:return l.Value;case ParenthesizedExpression p:return "("+Emit(p.Expression)+")";case UnaryExpression u:return (u.Operator=="not"?"!":u.Operator)+Emit(u.Operand);case BinaryExpression b:return Emit(b.Left)+" "+(b.Operator=="and"?"&&":b.Operator=="or"?"||":b.Operator)+" "+Emit(b.Right);case CallExpression c: if(c.Name=="not-seen-recently")return Emit(c.Arguments[0].Expression)+".notSeenRecently("+Emit(c.Arguments[1].Expression)+")"; return Name(c.Name)+"("+string.Join(",",c.Arguments.Select(a=>(a.Name==null?"":a.Name+":")+Emit(a.Expression)))+")";default:return "default";}}
 static string Name(string n){var x=n.Contains('-')?DslNames.Camel(n):n;return x is "object" or "string" or "int" or "bool"?"@"+x:x;}
 static string Type(string t)=>t=="int"?"int":t=="bool"?"bool":t=="string"?"string":t=="DateTime"?"System.DateTime":t;
}
