<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)generated</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Segusum.AspNetCore\Segusum.AspNetCore.csproj" />
    <ProjectReference Include="..\..\Segusum.Scripting.Generator\Segusum.Scripting.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\..\Segusum.Scripting.Core\Segusum.Scripting.Core.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <AdditionalFiles Include="Scripts\**\*.seg" />
  </ItemGroup>
</Project>
