//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seg
{
    using System;
    using Microsoft.EntityFrameworkCore;
    
    public partial class segusumDb : DbContext
    {
        public segusumDb()
            : this(CreateDefaultOptions())
        {
            FilePersistence.Load(this);
        }

        private static DbContextOptions<segusumDb> CreateDefaultOptions()
        {
            var builder = new DbContextOptionsBuilder<segusumDb>();
            if (StorageOptions.IsFile)
                builder.UseInMemoryDatabase(StorageOptions.InMemoryDatabaseName);
            else
                builder.UseSqlServer(StorageOptions.ConnectionString);
            return builder.Options;
        }

        public segusumDb(DbContextOptions<segusumDb> options)
            : base(options)
        {
            FilePersistence.Load(this);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<user>().ToTable("user");
            modelBuilder.Entity<ips>().ToTable("ips");
            modelBuilder.Entity<savegame>().ToTable("savegame");
            modelBuilder.Entity<UnhandledCombination>().ToTable("unhandledCombination");
            modelBuilder.Entity<AdminNarrativeMessage>().ToTable("adminNarrativeMessage");

            modelBuilder.Entity<user>().HasKey(x => x.id);
            modelBuilder.Entity<user>().Property(x => x.isCasualMode).HasDefaultValue(false);
            modelBuilder.Entity<ips>().HasKey(x => x.id);
            modelBuilder.Entity<savegame>().HasKey(x => x.id);
            modelBuilder.Entity<UnhandledCombination>().HasKey(x => x.id);
            modelBuilder.Entity<AdminNarrativeMessage>().HasKey(x => x.id);
            modelBuilder.Entity<UnhandledCombination>()
                .HasIndex(x => new { x.gameId, x.category, x.firstId, x.secondId })
                .IsUnique();
            modelBuilder.Entity<ips>().HasOne(x => x.user).WithMany(x => x.ips)
                .HasForeignKey(x => x.idUser);
            modelBuilder.Entity<savegame>().HasOne(x => x.user).WithMany(x => x.savegame)
                .HasForeignKey(x => x.idUser);
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                if (StorageOptions.IsFile)
                    optionsBuilder.UseInMemoryDatabase(StorageOptions.InMemoryDatabaseName);
                else
                    optionsBuilder.UseSqlServer(StorageOptions.ConnectionString);
            }
        }
    
        public virtual DbSet<ips> ips { get; set; }
        public virtual DbSet<savegame> savegame { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<UnhandledCombination> unhandledCombination { get; set; }
        public virtual DbSet<AdminNarrativeMessage> adminNarrativeMessage { get; set; }
    }
}
