//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seg
{
    using System;
    using System.Collections.Generic;
    
    public partial class savegame
    {
        public int id { get; set; }
        public string savegameXml { get; set; }
        public int idUser { get; set; }
        public int idStory { get; set; }
        public string savegameTitle { get; set; }
        public Nullable<System.DateTime> dateModified { get; set; }
    
        public virtual user user { get; set; }
    }
}
